### ISSUE TITLE
Test w/ v2

### ISSUE THREAD

**Issue by JaneJeon** [oscaroox/objection-visibility#10]
Hi, as simple as this library is, we should still test it for objection v2 (and v1, if you want).

This also gives you the opportunity to bump this plugin to v1.0.0 (especially so if you were to drop support for objection@1).

Thoughts? (e.g. do you want to support both v1 and v2)

P.S. if you want to look at an example of how to support both v1 and v2, see here: https://github.com/JaneJeon/objection-hashid/blob/master/index.test.js#L11 and here: https://github.com/JaneJeon/objection-hashid/blob/master/package.json#L50

**Comment by oscaroox** [comment]
Hi @JaneJeon sorry for the late reply, Dropping support for v1 seems to be the correct decision. I will update the tests in the coming  days

**Comment by oscaroox** [comment]
Tested with objection ^2. Luckily tests didn't fail.
