### ISSUE TITLE
Objection-Visibility support for newer objection versions

### ISSUE THREAD

**Issue by fitimbyttyqi** [oscaroox/objection-visibility#22]
Hello guys,

First of all, thanks for creating such plugins that make our life easier :).

I was wondering if it's possible for this package to have support for the newer versions of objection js (3 >) because when trying to install npm packages I get this error.

`
While resolving: ...
npm ERR! Found: objection@3.0.1
npm ERR! node_modules/objection
npm ERR!   objection@"^3.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer objection@">= 2 < 3" from objection-visibility@1.1.0
npm ERR! node_modules/objection-visibility
npm ERR!   objection-visibility@"^1.1.0" from the root project
`

Currently, I see that in package.json objection js peer dependency is supported for versions less than 3 of objection.

` "peerDependencies": {
    "objection": ">= 2 < 3"
  }
  `

**Comment by fitimbyttyqi** [comment]
@oscaroox Thanks a lot, by 3 do you mean 3/up or just 3?

**Comment by oscaroox** [comment]
It should be fixed now, you can pull v1.2.0 from npm. let me know if it works then i can close this issue
