### ISSUE TITLE
Option to hide or not columns

### ISSUE THREAD

**Issue by chamini2** [oscaroox/objection-visibility#3]
I currently need to hide information sometimes and sometimes not (depending if the user obtaining it is an admin).

```ts
export class User extends Model {
  public static tableName = 'users';
  public static idColumn = 'id';

  public static get hidden(): string[] {
    const always = [ 'password' ];
    const personal = [ 'email', 'phone_number' ];

    return concat(always, personal);
  }
  public email: string;
  public phone_number string;
  public password string;
}
```

I want to return the `email` and `phone_number` of a user only to admins.

I was thinking of setting a _per-instance_ property `showHidden: boolean` that I could turn to `true` when I wanted this information, but I have no way to ask for the instance's `showHidden` value in the `get hidden` function.

*****

I was wondering if you have considered this somehow, and if not, if you would be willing to consider it. Maybe in another way that my proposal, but somehow.

**Comment by oscaroox** [comment]
I don't think this plugin should be able to hide properties based on outside parameters like user roles, this should be done in your controller/routes.

I think you should map your user class to a viewmodel class instead. I think this is the best way to handle
what properties are shown if an admin requests a user . With this solution you can still use the plugin to hide password for both admins and a regular user.

example
```js
class AdminViewModel {
  public email: string;
  public phone_number: string;
  constructor(email: string, phone_number:string) {}
}

app.get('/admin-only', (req, res) => {
  let user = User.query().findOne(1);
  
  if(req.user.isAdmin) {
   // only admin can see email and phone_number
    return res.json(new AdminViewModel(user.email, user.phone_number))
  }
  // else return for user
})
```
what do you think?

**Comment by chamini2** [comment]
Awesome! Great idea. Thanks!

**Comment by akylkb** [comment]
My decision:
```javascript
class User extends Model {
  static get tableName () {
    return 'users'
  }

  static get modifiers () {
    return {
      defaultSelect (builder) {
        builder.select([
          'id',
          'name'
        ])
      },

      personalSelect (builder) {
        builder.select('*')
      }
    }
  }

  static get hidden () {
    return [
      'password'
    ]
  }
}
```
UserController
```javascript
const publicData = await User.query().modify('defaultSelect')
const privateData = await User.query().modify('personalSelect') 
```
