### ISSUE TITLE
docs: worth mentioning that library returns default

### ISSUE THREAD

**Issue by fl0w** [oscaroox/objection-visibility#6]
For those now using TS or transforming import-statements, the library is exported as:
```js
{ default: [Function] } // ready for ESNext import
```
Thus, following docs example yields a TypeError.
Fixed with a destruct alias:
```js
const { default: visibilityPlugin } = require('objection-visibility')
```

**Comment by oscaroox** [comment]
@fl0w thanks for reporting this, will update docs soon. I was actually trying to get away from default exports to named exports.
